#!/usr/bin/env python
"""Generate Server tool stubs from shared definitions.

This script generates Server-side @fusion_tool decorated stub functions
from the shared tool definitions. This ensures the Server always matches
the single source of truth.

Usage:
    python scripts/generate_server_stubs.py           # Preview what would be generated
    python scripts/generate_server_stubs.py --write   # Write to files
    python scripts/generate_server_stubs.py --diff    # Show diff against existing
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add parent directory to path for imports
ROOT_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT_DIR))

from shared.tool_definitions import (
    ToolDef,
    get_tools_by_category,
    list_categories,
)


def generate_function_stub(tool: ToolDef) -> str:
    """Generate a @fusion_tool decorated function stub."""
    lines = []

    # Decorator
    decorator_args = []
    if tool.endpoint != tool.name:
        decorator_args.append(f'endpoint="{tool.endpoint}"')
    if tool.http_method == "GET":
        decorator_args.append('method="GET"')
    if not tool.use_sse:
        decorator_args.append("use_sse=False")

    if decorator_args:
        lines.append(f"@fusion_tool({', '.join(decorator_args)})")
    else:
        lines.append("@fusion_tool")

    # Function signature
    params_str = tool.get_signature_params()
    lines.append(f"def {tool.name}({params_str}):")

    # Docstring
    lines.append('    """')
    lines.append(f"    {tool.description}")

    if tool.params:
        lines.append("    ")
        lines.append("    Args:")
        for p in tool.params:
            default_note = "" if p.required else f" (default: {p.default})"
            lines.append(f"        {p.name}: {p.description}{default_note}")

    if tool.returns:
        lines.append("    ")
        lines.append("    Returns:")
        lines.append(f"        {tool.returns}")

    lines.append('    """')
    lines.append("")  # Empty function body (stub)

    return "\n".join(lines)


def generate_category_module(category: str, tools: list[ToolDef]) -> str:
    """Generate a complete module for a category of tools."""
    lines = [
        f'"""Auto-generated {category.title()} tools for Fusion 360 MCP Server.',
        "",
        "This file was generated by scripts/generate_server_stubs.py from",
        "shared/tool_definitions.py. Do not edit directly!",
        "",
        "To update, modify shared/tool_definitions.py and regenerate.",
        '"""',
        "",
        "from .base import fusion_tool",
        "",
        "",
    ]

    for tool in tools:
        lines.append(generate_function_stub(tool))
        lines.append("")

    return "\n".join(lines)


# Map categories to Server module names
CATEGORY_TO_MODULE = {
    "primitives": "primitives",
    "sketches": "sketches",
    "extrusions": "operations",
    "operations": "operations",
    "patterns": "patterns",
    "transform": "transform",
    "measurement": "measurement",
    "parameters": "parameters",
    "utility": "utility",
}


def preview_generation():
    """Preview what would be generated."""
    print("=" * 60)
    print("Preview of generated Server stubs")
    print("=" * 60)

    for category in list_categories():
        tools = get_tools_by_category(category)
        if not tools:
            continue

        module_name = CATEGORY_TO_MODULE.get(category, category)
        print(f"\n\n{'=' * 60}")
        print(f"Category: {category} -> Server/src/tools/{module_name}.py")
        print(f"Tools: {len(tools)}")
        print("=" * 60)

        for tool in tools:
            print(f"\n{generate_function_stub(tool)}")


def show_single_tool_stub(tool_name: str):
    """Show stub for a single tool."""
    from shared.tool_definitions import get_tool

    tool = get_tool(tool_name)
    if tool:
        print(generate_function_stub(tool))
    else:
        print(f"Tool '{tool_name}' not found in shared definitions")


def main():
    parser = argparse.ArgumentParser(description="Generate Server tool stubs")
    parser.add_argument("--write", action="store_true", help="Write to files")
    parser.add_argument("--diff", action="store_true", help="Show diff against existing")
    parser.add_argument("--tool", type=str, help="Generate stub for a single tool")
    parser.add_argument("--category", type=str, help="Generate stubs for a category")
    args = parser.parse_args()

    if args.tool:
        show_single_tool_stub(args.tool)
        return

    if args.category:
        tools = get_tools_by_category(args.category)
        if tools:
            print(generate_category_module(args.category, tools))
        else:
            print(f"No tools found for category '{args.category}'")
            print(f"Available categories: {list_categories()}")
        return

    preview_generation()

    if args.write:
        print("\n⚠️  --write not fully implemented yet.")
        print("    The generated stubs should be manually reviewed before replacing")
        print("    existing code, as some modules may have additional imports or logic.")


if __name__ == "__main__":
    main()
